services:
  redis:
    image: redis:8.2.0-alpine
    container_name: auth_redis
    ports:
      - "6379:6379"
    restart: always


  postgresql:
    image: postgres:17-alpine
    container_name: auth_postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    
  prometheus:
    image: prom/prometheus:latest
    container_name: auth_prometheus_container
    ports:
      - "9090:9090"
    restart: always
    volumes:
      - ./docker/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:z
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
  node-exporter:
    container_name: node_exporter_container
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
      
  grafana:
    image: grafana/grafana:latest
    container_name: auth_grafana_container
    ports:
      - "3000:3000"

  jaeger:
    image: jaegertracing/all-in-one:1.72.0
    container_name: jaeger_container
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=:9411
    
  auth_microservice:
    build:
      context: .
      dockerfile: docker/Dockerfile.HotReload
    container_name: auth_microservice_container
    ports:
      - "5001:5001"
      - "5555:5555"
      - "7070:7070"
    depends_on:
      - redis
      - postgresql
      - prometheus
      - node-exporter
      - grafana
      - jaeger
    environment:
      - config=docker
    restart: always
    volumes:
      - ./:/app
      
volumes:
  pgdata: