server:
  AppVersion: 1.0.0-docker
  Port: :5001
  ProfPort: :5555
  Mode: Development
  JwtSecretKey: secretKey
  CookieName: jwt-token
  ReadTimeout: 10
  WriteTimeout: 10
  SSL: true
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: false
  Timeout: 15
  MaxConnectionAge: 5
  Time: 2

postgres:
  Host: localhost
  Port: 5432
  User: postgres
  Password: postgres
  Dbname: auth_db
  SSLMode: false
  PgDriver: pgx

redis:
  RedisAddr: localhost:6379
  RedisPassword:
  RedisDB: 0
  RedisDefaultdb: 0
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240
  Password: ""
  DB: 0

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: console
  Level: info

jaeger:
  Host: http://localhost:14268/api/traces
  ServiceName: AUTH_GRPC_SERVER
  LogSpans: true

metrics:
  Url: 0.0.0.0:7070
  ServiceName: AUTH_MICROSERVICE

rabbitmq:
  Host: localhost
  Port: 5672
  User: guest
  Password: guest
  Exchange: emails_exchange
  Queue: emails_queue
  RoutingKey: emails_routing_key
  ConsumerTag: emails_consumer
  WorkerPoolSize: 24

smtp:
  Host: smtp.gmail.com
  Port: 587
  User: your_email@gmail.com
  Password: your_pass